app/components/shared/Panel/intro-with-button.js
I'm not sure how this ever worked… but it def broke if the panel text was smaller than the whole width
=> Fix the flex on panels with buttons

app/components/shared/Menu/button.js
Before:
After:
I also made the badge class more declarative using jsx and functions, and less imperative/code style. I think for UI components trying to keep it as tags and props and not putting too much JS in there means that you can more easily see how it’s working at a glance.
Also: no more need for `Features.NewNav`! :)
=> Fix menu badge on Firefox

app/components/shared/FormMarkdownEditorField.js
By default a browser uses the first button in the form with `type=submit` or no type at all when you submit a form with the keyboard. So if there's another field in the form, such as a Changelog Title, and you hit enter… the bold button would be clicked.
This just corrects the type of the buttons so they don't trigger on form submit.
=> Add type="button" so they don't end up as submit buttons

app/components/layout/Navigation/index.js
To help people see that they can add users, this adds Users to the top nav:
I'm not 100% sold on it here, but without a nav rejig I'm not sure what another solution is for now.
=> Add Users to the top nav

app/components/organization/Show.js, app/components/team/Edit.js, app/components/team/Form.js, app/components/team/Index.js, app/components/team/Members/role.js, app/components/team/New.js, app/components/team/Row.js, app/components/team/Show.js
Some components have rather generic names, this updates them with their category if they have one.
Possibly worth discussing; some existing components have a `displayName` attribute applied, which sort of goes for a namespace-ish approach - which is more desirable here?
=> Improve naming of components

app/app.js, app/queries/Agent.js, app/queries/Build.js, app/queries/Organization.js, app/queries/Pipeline.js, app/queries/PipelineSchedule.js, app/queries/Team.js, app/queries/Viewer.js
This is in preparation for making the navigation use Relay always, which requires us to optionally use these queries in pre-ES6 code, thus exporting them to `window.Webpack`
=> Split out queries into their own files

app/components/organization/Pipeline/build-tooltip.js, app/components/organization/Pipeline/status.js
From the _I-need-this-somewhere-other-than-git-stash_ department
=> Improved pipeline tooltip, with duration and status

.buildkite/jest.sh, .buildkite/pipeline.yml, .eslintignore, Dockerfile, app/app.js, app/components/icons/BuildState.js, app/components/organization/Pipeline/build-tooltip.js, app/components/shared/Dropdown.js, app/components/user/BuildsDropdown/build.js, app/components/user/BuildsDropdown/index.js, app/lib/__snapshots__/commits.spec.js.snap, app/lib/commits.js, app/lib/commits.spec.js, docker-compose.yml, npm-shrinkwrap.json, package.json
This brings the my builds dropdown and build tooltip into line with each other.
Both now have a semi-bold first-line of commit message displayed, as well as the shortened commit-ish, and use consistent colours and sizes.
This branch also;
- fixes some ESLint warnings
- breaks out some repeated commit metadata handling into a shared function library
=> More consistent build dropdown and tooltip

app/components/layout/Navigation/index.js, app/components/organization/Teams.js, app/components/shared/Icon/down-triangle.js, app/components/shared/Icon/index.js
I went to fix this Firefox bug:
and then I accidentally fixed all the dropdown triangles to be nicer than unicode:
They also look nice on mobile now too:
=> Replace unicode down triangles with real icons

app/components/icons/BuildState.js
also fixes a rounding error in Safari (wherein the small versions would spin off-centre), but the first bit sounds cooler
instead of spinning the entire SVG, we now spin just the mask, which means it’s rendered within the SVG, which means it’s all antialiased properly for the orientation it’s in
=> Make BuildState animations crisp AF

app/components/icons/BuildState.js, app/components/icons/BuildState.spec.js, app/components/icons/__snapshots__/BuildState.spec.js.snap, npm-shrinkwrap.json, package.json
Switching to UUID should prevent collisions, and mixed up states. There is probably a better approach to this, however.
=> Isolate BuildState icon SVG element references

app/components/organization/Pipeline/build-tooltip.js, app/components/user/BuildsDropdown/build.js, app/css/text.css
=> Fix overflow issue with long build names that don't have spaces

app/components/layout/Navigation/index.js
This seems more consistent with the organization selector and user menus
=> Add an arrow to the My Builds dropdown

app/components/icons/Favorite.js, app/lib/__snapshots__/builds.spec.js.snap, app/lib/__snapshots__/date.spec.js.snap, app/lib/builds.js, app/lib/builds.spec.js, app/lib/date.js, app/lib/date.spec.js
- disallows negative time spans (note: this means `from` *must* be before `to`; this might need revision in future?)
- falls back to `scheduledAt` for `blocked` or `canceled` builds without `startedAt`
- adds specs around these edge cases
=> More robust relative date handling

app/lib/__snapshots__/builds.spec.js.snap, app/lib/builds.js, app/lib/builds.spec.js
Certain builds which can enter a finished state do not have a `startedAt`, but do have a `scheduledAt`. This takes that value for the start time, which fixes graphing of those times!
=> Make buildTimer fall back to scheduledAt

app/components/organization/Pipeline/graph.js, app/components/organization/Pipelines.js
This avoids the triple-loop method we currently use, which should make a future version (insert sparkle emoji here✨) able to either paginate, or render the first N graphs before rendering the rest.
This was part of more perf investigation after shipping #95
=> This is a tiny optimisation of the pipeline render

app/lib/__snapshots__/builds.spec.js.snap, app/lib/builds.js
This changes the tooltip text from:
to "Failed Tuesday at 2:33 PM"
Which is important because at the moment, colour is the only way to differentiate the builds in the build graph… there's no icon or words to tell people what the difference between passed and failed graphs are.
=> Finished -> Passed/Failed

app/components/organization/Pipeline/bar.js, app/components/organization/Pipeline/graph.js
It turned out the bug in the graph rendering was actually nothing to do with the build _state_ at all, but that newer, quick build graphs were never shrunk by the longer build times following them!
Before:
After:
=> Fix graph calculations

app/components/layout/Navigation/index.js
This allows My Builds to wrap within the menu bar, and remain centered vertically, rather than bleeding off the edge of the menu bar. There's still a lot to optimise in this menu, but this fixes one major bother of mine, at least :P
=> Improve header button wrapping behaviour

app/components/agent/Index/agentTokens.js, app/components/agent/Index/agents.js, app/components/agent/Index/index.js, app/components/agent/Index/row.js
This change will defer the loading of the agents and the tokens until the main page has mounted. They show a spinner until the data is available. This stops the page from blocking until all the data is available - which is a bit nicer on the eyes.
I also rearranged the code a little bit and split things out into seperate components.
=> Defer data loading on Agents Page

app/components/shared/Badge.js, app/css/fonts.css
This makes the badges less prone to little changes in layout thanks to changing numbers - they'll only change width if there's a new significant digit (where fitted).
Here’s an image from the CSS fonts level 3 spec, demonstrating proportional and tabular numerals;
And here’s how it changed on Buildkite;
🔜
=> Use tabular numerals in navbar badges

app/components/shared/Duration.js, app/components/shared/__snapshots__/Duration.spec.js.snap
Before:
After:
This will apply to all the pipeline tooltips too.
=> Use tabular numerals for durations too

app/components/layout/Navigation/index.js
Things are getting a little cramped on smaller screens:
This hides the username from medium and small sized screens, and only shows it on extra-small (mobile, when it goes to two rows) and large.
=> Hide username on mid-sized screens

app/lib/Emoji.js, app/lib/__snapshots__/Emoji.spec.js.snap
This updates the Emoji class to produce copyable output which, in all cases, would produce the same output if put through the parser again.
The alt text for non-unicode emoji is now shown as the same colon-wrapped version we accept as input, whilst Unicode emoji continues to use the Unicode representation.
=> Lossless emoji replacement

app/components/organization/Pipeline/build-tooltip.js, app/components/shared/Duration.js, app/components/shared/Duration.spec.js, app/components/shared/__snapshots__/Duration.spec.js.snap, app/components/user/BuildsDropdown/build.js
This applies tabular numerals to most usages of the build timer component.
These places spend a lot of time counting in real-time, and frankly look a little funny flopping all over the place!
The exception to this is the my builds dropdown, and the build tooltip, where the build timer is in “micro” format, and isn’t presented within a sentence - those stay as they were!
=> Tabular numerals in build timers

app/css/container.css
Previously, the boundary sizes described by our breakpoints would overlap, causing ssingle-pixel sizes where behaviours were inconsistent.
This fixes this by subtracting one pixel from the max-width definitions of each breakpoint type.
=> Fix breakpoint misses

app/components/layout/Navigation/index.js, app/components/organization/Teams.js, app/components/shared/Dropdown.js, app/components/team/Members/role.js, app/components/team/Pipelines/access-level.js, app/components/user/BuildsDropdown/build.js, app/components/user/BuildsDropdown/index.js, app/css/transitions.css
**Before:**
**After:**
- makes the dropdown viewport-aware
- Dropdowns with `align="center"` (now the default) will automatically position (and resize, if necessary) themselves to stay within the viewport!
- they'll make sure their bodies are visible, set the position of their nibs to match their parents, and set their `transformOrigin` to line up (bonus points: `transformOrigin`s for centered Dropdowns were actually previously slightly wrong!)
- resizing is handled with intelligent debouncing;
- if a dropdown is shown, it'll update every 100ms until resizing ceases, which seems to be about the right spot for it to feel right
- if a dropdown isn't shown, we're rather lazier and only update 250ms after the last resize event (this is good because reading DOM layout is expensive!)
- *all* …
=> Make Dropdowns viewport-aware

app/app.js, app/components/build/UnblockPromptRequiredFieldNotice.js
To let users know that unblock fields are now required by default
=> Unblock Prompt Fields Notice

app/components/layout/Navigation/index.js
When a use has scrollbars forced on (mouse is plugged in, using a tablet) and `overflow` properties are set to `scroll`, scrollbars are always shown. On OSX by default, most scrollbars sit above the content, whereas when they are shown they collapse the content. With this change, scrollbars are shown when the screen is small and the content is wide, but not triggered in the default case.
**Previously (note the weird gray lines on the secondary navigation):**
**After the fix:**
_Wide:_
_Thin:_
=> Make navigation scrollbars lazy

app/components/layout/Navigation/dropdown-button.js
Descenders in the organization and user dropdown buttons were cut off, as their line-heights were 1. This sets them (using `.line-height-3`) to `1.25em`, which provides enough clearance for descenders, and doesn't affect their vertical position because Thanks, Flexbox™!
**Before:**
**After:**
fixes https://3.basecamp.com/3453178/buckets/2169122/todos/323587909
=> Treat those descenders right

app/components/layout/Navigation/index.js, app/components/shared/Button.js, app/components/user/BuildsDropdown/index.js
At the moment if you don't have your emails configured correctly, or you're a new user, this is what you see when you click on My Builds:
The problem is that "you haven't created any builds yet" could be untrue. They could have created builds, they just haven't added their commit email address to their list of Buildkite email addresses.
* Handles the case where people aren't using git, but some other SCM and using the API (that's why the `git config user.email` is just an example, and it's referred to as "commit email" instead of "git config email" or "git email".
* Helps to remind them what the command is to find out what git commit email they're using.
* Makes the dropdown a bit wider to fit the text. I wanted to do anyway because it gets a bit cramped and tall sometimes even though …
=> More explicitly connect git commit email with My Builds

app/components/layout/Navigation/MyBuilds/index.js, app/components/layout/Navigation/dropdown-button.js
So I've tweaked the data loading of the dropdown to be a bit smarter to avoid the spinner as much as possible.
1. When the page loads, it uses the build numbers from the cache, shows them first.
2. After Pusher has connected, it refetches the latest values from GraphQL.
This ensures that we have the latest values, and we'll be notified when we get new ones.
When it comes to loading the actual builds:
- We start preloading the data on "mouse enter" to reduce the initial spinner time. Doesn't matter if they decide not to load it anyway
- If we receive a "user builds change" Pusher event, we refresh the "builds" and "counts", and render them at the same time. We ignore the data from pusher (which does include the latest build counts), but we'll refetch from GraphQL and use those as the …
=> Refactored "My Builds" data loading

app/components/icons/BuildState.js, app/components/icons/BuildState.spec.js, app/components/icons/__snapshots__/BuildState.spec.js.snap, app/components/organization/Pipeline/graph.js
Currently this adds a "Cancelling" build state icon, which is the same as running build but red (the same as cancelled, which is a red cross). So the icon change will be from grey spinning to red spinning.
The current handled states are:
- `pending`
- `scheduled`
- `running`
- `passed`
- `blocked`
- `failed`
- `canceled`
- `canceling`
Are we missing any others?
Closes #147
=> Add missing build state icons

app/app.js, app/components/layout/Navigation/index.js, app/components/organization/AgentsCount.js, package.json, yarn.lock
This updates the AgentsCount component to be Relay-aware, and instead of alternatingly trusting the Pusher agent count and Relay agent count, instead takes a change on the Pusher end as a cue to `forceFetch` updated values from Relay.
This causes the component to stay pretty stable when it comes to repaints.
I also took the opportunity to switch over to using `shallowCompare` in `shouldComponentUpdate` and remove the component from the Webpack bridge in app.js
Fixes https://3.basecamp.com/3453178/buckets/1445180/todos/323608085
=> Fix AgentsCount inconsistencies

app/components/build/AvatarWithUnknownEmailPrompt.js
Before we'd show the prompt even if there was an associated user. This changes the code so it'll only prompt if GraphQL says: "hey, we actually don't have a user here"
=> Only show the email prompt if theres no associated user

app/components/layout/Navigation/index.js, app/components/user/NewChangelogsBadge.js
Previously, it suffered from the same state caching issues as other Pusher-powered things that could also be interacted with (opening, for instance, the Organizations dropdown, would cause it to use the cached state), this updates it to act correctly in all cases.
It also makes it a relay container which accepts the isMounted variable from its parent, so that it can force an update of only its data set whilst also being updated on-mount without triggering a separate request for its data!
=> Make the Changelogs badge bulletproof

app/components/shared/__snapshots__/Duration.spec.js.snap, app/lib/__snapshots__/date.spec.js.snap, app/lib/date.js, app/lib/date.spec.js
A bug existed which meant the most significant unit of duration would be shown including the value of next most significant unit of duration. This caused strangely divergent results between `micro` and `full` date rendering.
This improves the logic which controls truncation and merging of duration segments, and fixes #165's issue. It also improves the output of the date spec suite (for best results, inspect the changes in 027b904, as they are _after_ the improved date spec suite was added)
=> Improved date formatting

app/components/layout/Navigation/index.js, app/css/background-colors.css, app/css/backgrounds.css, app/css/main.css
This adds an `assuming` prop to `Navigation`, so we can make it clearer when you're assuming a user:
=> Make it clear when assuming a user

app/components/organization/Pipeline/status.js
For older builds with larger timestamps, the pipelines build popover width can be too narrow to fit the last line:
Instead of using the default `AnchoredPopover` width of 250, this sets it explicitly to 300 which covers most cases for the last line.
=> Fix awkward timestamp line breaks in build popovers

app/components/organization/Pipeline/bar.js
Missed in #172, this makes sure the pipeline graph build tooltips are also wide enough to fit timestamps
=> Made pipeline tooltips 300px wide too

app/components/layout/Navigation/index.js, app/components/organization/Pipelines.js, app/stores/SessionHashStore.js
This pull request persists the last selected* team for a given Organization to a user’s localStorage, and updates the Navigation link to match.
_*this means it can get inconsistent when switching tabs, which is a bit weird, but hey_
=> Sticky team selections: Chunk 1, Frontend amazingness

app/components/agent/Index/agents.js, app/components/agent/Index/search.js
Changes to remote search (> 100 agents):
* Sends the query to the server on every keyup
* Only shows a spinner if the search is taking > 1 second
* The spinner now lives next to the search field
* Fixes a bug where local search could be triggered by accident
Changes to local search (< 100 agents):
* Filters immediately on keyup
* Fixes the matching logic to match the backend/remote matching logic
=> Improved agent searching

app/components/build/StateSwitcher.js, app/components/organization/NewPipelinesPageNotice.js, app/css/btn.css
This tweaks the `.btn` class’ line-height to `1.2`, rather than `1`. This fixes a lot of our `.btn`-derived elements chopping descenders off their text content.
A couple of components which stood out as having been affected negatively by this change have been updated. Those components also had `shallowCompare` applied because why not. :sparkles:
=> Less harsh button line height

app/components/agent/Index/agent-tokens.js, app/components/agent/Index/index.js, app/components/agent/Index/quick-start.js, app/components/docs/09-aws/parameter-table.js
This change removes the initial full page spinner from showing the new Agents Page. It also changes the Agents page so it looks the same for all users - regardless of whether or not they have access to view Agent Registration Tokens.
=> Remove full page Agents Page spinner

webpack/config.js
For a while our WebPack chunking has been broken. For example, `RelayRecordWriter` shouldn't appear anywhere in our `app.js` bundle:
```
$ curl -s https://buildkiteassets.com/frontend/955d7d07c58846c1b0fc2cfeeb1c6abbbd078b33/app-435291416144e82caf08.js | grep -i 'RelayRecordWriter' | wc -l
2
```
This updates our webpack config to output the correct chunks.
Before:
```
$ ls -l dist/*
-rw-r--r-- 1 tim  11M Feb 26 21:48 dist/app.js
-rw-r--r-- 1 tim 793K Feb 26 21:48 dist/emojis.js
-rw-r--r-- 1 tim 3.5K Feb 26 21:48 dist/loader.js
-rw-r--r-- 1 tim  240 Feb 26 21:48 dist/manifest.json
-rw-r--r-- 1 tim 114K Feb 26 21:48 dist/public.js
-rw-r--r-- 1 tim 7.8M Feb 26 21:48 dist/vendor.js
$ grep -i 'RelayRecordWriter' dist/vendor.js | wc -l
3
$ grep -i 'RelayRecordWriter' dist/app.js | wc -l
3
``` …
=> Fix WebPack chunking

app/components/organization/Pipelines.js
=> Sticky team selections: Follow up, Handle GraphQL failures from missing teams

app/components/pipeline/teams/Index/index.js, app/components/shared/AutocompleteField/error-message.js, app/components/shared/AutocompleteField/index.js, app/components/shared/AutocompleteField/suggestion.js, app/components/team/Members/index.js, app/components/team/Pipelines/index.js
The Autocomplete Field does not act like other components prefixed with `Form-` (which as far as I can tell are intended as a consistent set of things for labeled, feedback-providing form controls), and that's currently the intended behaviour.
This, therefore, renames it to `AutocompleteField` to remove the implication that they're related.
=> Rename the Autocomplete field

.babelrc, package.json, yarn.lock
Even though these tools are deprecated, they actually seem more stable than the current tools that are recommended that solve the hot module reloading problem.
Turns out it wasn't working before because we were running an old version of webpack-dev-server. Once that was bumped, this old gear started working as usual without a hitch.
Hopefully by the time these tools stop working, the new tools will work better.
=> Added back react-transform-hmr and friends

webpack/config.js
Thanks to #210 I spotted a few missing vendor libs.
Before:
After:
Also, [this Twitter thread](https://twitter.com/TheLarkInn/status/842817690951733248) ([#whatsinyourbundle](https://twitter.com/hashtag/whatsinyourbundle)) from Sean Larkin on the Webpack core team has lots of gold.
I think the next biggest wins are:
* Remove inlining of images in the JS as base64
* Move a whole bunch of components out to only load on demand, with a few nice touches ala [react-loadable](https://medium.com/@thejameskyle/react-loadable-2674c59de178#.vxo622qxr)
=> Add a few missing vendor libs

app/components/shared/Panel/row-link.js
Previously, it was possible for large children to cause the chevron on the right of the RowLink to shrink.
Also updates the component with `shouldComponentUpdate`!
=> Panel.RowLink: Disallow shrinking chevron icon

app/components/team/Row.js
=> Handle large team sizes in Team list

webpack/config.js
This prevents an extraneous error from being thrown in production. `react-type-snob` is neither referred to nor used in production and can thus be safely removed!
Also adds a throw when no `EMOJI_HOST` is set, which means you get a failure after 0.5 seconds rather than 90.
=> Remove react-type-snob from the `vendor` bundle

.buildkite/steps/bundle-analyze.sh
It looks like we were running two production builds in the bundle analyser step. This removes the first, which hopefully should halve the job's time!
=> Don't build twice when analysing bundle

app/components/agent/Index/installation.js, app/components/agent/Index/quick-start.js, app/components/agent/Show.js, app/components/build/AvatarWithUnknownEmailPrompt.js, app/components/layout/Navigation/support-dialog.js, app/components/organization/Pipeline/Metrics/metric.js, app/components/organization/Pipeline/index.js, app/components/organization/Teams.js, app/components/organization/Welcome.js, app/components/pipeline/Header/index.js, app/css/main.css, app/css/style-guide/index.js, app/css/style-guide/typography.js
As part of working on the new pipeline header updates, I updated these font-sizes. I'm breaking these sorts of changes out into their own PRs so we can ship them first.
This one updates our type scale to be more sane. `.h4` is now "regular sized text", and we actually define a `.h2` size.
Whilst working on the sizes I needed a style guide I could change and look at, and I left it in there with the idea that we'd mount it to `_styleguide` in development. I just gave up on making that actually work.
=> Clean up type sizes

app/components/job/Index/index.js, app/components/job/Index/state-selector.js
Currently the "all" query kills the DB, so we'll restrict the state list to active jobs (a much-smaller subset than all historical jobs") and we'll default it to show "scheduled" jobs. If we fix the performance problems, we can revert this back
=> Limit job listing to a much smaller subset of jobs

app/components/layout/Navigation/support-dialog.js, app/components/shared/Dialog.js
This allows the dialog to scroll. What it does is rearrange the dialog to allow the entire dialog to appear partially offscreen, and the rest to scroll into view.
This has a couple of caveats, which might be acceptable or might need working around.
In any case, this is intended in support of #222, which can in some cases create dialogs which appear partially offscreen, and currently can't be scrolled to.
The caveats;
* Scrolling the dialog requires the cursor to be over the dialog, not the dialog backdrop
* This is because the scroll container is transparent so the scroll event is passed to the backdrop, which is not part of a scroll container, and thus passed to the page.
* We can work around this by putting the backdrop in the scroll container, but we need to think more about how we …
=> Improve Dialog behaviour

app/components/team/Pipelines/chooser.js, app/components/team/Pipelines/index.js
Relay.Mutation does totes weird things when you use the autocomplete on the team show a bunch. When ever you search for a pipeline, it internally creates a new "relay connection" it's cache. If you search for 5 different things, it'll create 5 different cache entires.
Now when you add a new pipeline a team, Relay will try to refresh those 5 relay connections, which results in invalid mutations.
This change bypasses the auto-magic Relay mutation gear and just use the underlying API which doesn't do auto-refreshing of cache connection blah blah stuff and things.
=> Use the mutation API directly in the Team Pipeline Chooser dialog

app/components/shared/Menu/button.js
=> Fix long menu items being cut-off on small screens

app/components/shared/Panel/header.js, app/components/shared/Panel/index.js
In general it's good to use semantic tags for accessibility, but not for styling, so let's use a h2 here for panel headers.
=> Make Panel.Header use a h2

app/components/shared/Icon/schedules.svg
Makes the schedules icon a similar darkness to the rest of the icons:
=> Bolder schedules icon

app/css/codemirror-additions.css
It's too small for tiny pipelines.
=> Give the YAML CodeMirror a min-height

app/components/organization/SettingsMenu.js, app/components/pipeline/SettingsMenu.js, app/components/shared/Menu/button.js, app/components/user/SettingsMenu.js, app/css/icons.css, app/lib/permissions.js
#248 introduced a bug where icons would be collapsed, and another where some menu items weren't properly truncated:
This fixes the two bugs by fixing the `flex` definitions. Rather than copy+pasting class names to every `<Icon>` the label and icon have been moved to props of the `<Menu.Button>`
This also removes the empty `flex-none` div in menu buttons without badges, and brings the icons a little closer to their labels.
=> Fix menu button icon collapsing

app/components/pipeline/Header/index.js
Whoops! It was using the old `bootstrap` utils so when you switched to a pure Bass page, the thingies stopped working.
=> Switch to use BassCSS responsible tools instead of bootstrap

app/components/pipeline/CreateBuildDialog.js, app/components/pipeline/Header/index.js
This was accidentally removed (read: not reimplemented!) after removing the feature flags in buildkite/buildkite#2089.
This restores the functionality to the new dialog!
Links like this will auto-fill the build dialog;
https://buildkite.com/buildkite/bash-example#new?message=Hi%20there%20this%20is%20a%20prefilled%20message&branch=develop&commit=ffffffff&env=BUILDKITE_ROCKS%3Dtrue
Supported parameters;
* `message`
* `commit`
* `branch`
* `env`
* `clean_checkout` (naming convention kept from previous Ruby/CoffeeScript handler for compatibility; `true` if `=== 'true'`)
=> Restore build dialog deep-link functionality

app/app.js, app/components/layout/Flashes/flash.js, app/components/layout/Flashes/index.js, app/lib/Logger.js, app/routes.js, app/stores/PusherStore.js, webpack/config.js
This pull request includes a couple of little quality of life improvements for our push events.
1. When Pusher is disconnected, we’ll show the user a notice that things won’t live-update. In the past the page would just silently not update. Hopefully this’ll make it easier to tell the difference between a connection blip and a real showstopper!
The notice is automatically dismissed when the connection is restored, and the user may dismiss it. Additionally, dismissing the notice will mean no new notification is created until the connection is restored at least once (this prevents notices _re_-appearing when going from `unavailable` -> `connecting` -> `unavailable`)
2. `NODE_ENV=development` Pusher logging is improved. Previously some logs were not shown as the logger wasn’t initialised in …
=> Better Pusher connection handling

app/components/pipeline/schedules/Edit.js, app/components/pipeline/schedules/Form.js, app/components/pipeline/schedules/Index/index.js, app/components/pipeline/schedules/Index/row.js, app/components/pipeline/schedules/New.js, app/components/pipeline/schedules/Show/build.js, app/components/pipeline/schedules/Show/index.js, app/components/shared/FormInputLabel.js, app/components/shared/FormTextField.js, app/components/team/Form.js
Some cleanups before we announce scheduled builds are live:
* Clarifies which fields are required
* Puts the description at the top before all the Hard Stuff
* Added more information about the the cron interval syntax, along with `@` extensions we support
* Made sure teams forms were consistent
There's some things that still need improving which people might ask:
* Such as "How do I change/update the "Creator" of the builds?"
* What happens if the "Creator" is removed from the org?
Before:
After:
Before:
After:
Before:
After:
=> Improve Schedules Build form labels and layouts

app/components/member/New.js
While investigating a flakey spec I noticed the invite page shows a _Teams_ section even if the organization doesn't have teams enabled:
This just checks the teams count and hides teams if there aren't any at all, which should be a reasonable check because there should at least be an _Everyone_ team at the moment, and at least one team otherwise:
Which reminds me, we should probably make sure there is always at least one team in an organization.
=> Hide invite teams without teams

app/components/member/Edit.js, app/components/member/New.js, app/components/shared/FormCheckbox.js, app/components/team/Edit.js, app/components/team/Form.js, app/components/team/New.js, app/components/team/Row.js, app/mutations/TeamCreate.js, app/mutations/TeamUpdate.js
Adds a checkbox to team create and edit forms to toggle whether a team is a "default" team:
Also marks which teams are default in the teams list:
And pre-selects default teams on the invite page:
I think my backend changes broke the team create and edit forms by making the default fields required as part of the mutation input so maybe should get these changes in asap.
=> Default teams

.buildkite/pipeline.yml, Dockerfile, docker-compose.override.yml, docker-compose.yml
Currently a docker image gets built for frontend, but only pushed to [`buildkiteci/frontend`](https://hub.docker.com/r/buildkiteci/frontend/), which I view as ephemeral build artifacts and prone to being deleted. 
This change adds a push step at the end that deploys a passing image to the more official [`buildkite/frontend`](https://hub.docker.com/r/buildkite/frontend/) with tags that indicate what git commit they contain. For now, this will have no practical impact on anything, but it provides public runnable images of our frontend that we can also possibly consume in our development environments.
This also adds a `docker-compose.override.yml` which is only read in development (specifically, when no config files are specified). This mounts in the project for actually development using …
=> Push a final image to 🐳 buildkite/frontend on master

Dockerfile, docker-compose.override.yml, docker-compose.yml, package.json
To fix security things, webpack-dev-server added a check for hostname in https://github.com/webpack/webpack-dev-server/issues/887. 
Unfortunately, they also used that host check as the address to bind to, with only 127.0.0.1 and localhost as exceptions. This breaks docker containers or proxies. 
The workaround is to set up a host entry in the container for `buildkite.dev` to point to `0.0.0.0`. This then still has the hostname check, but it binds to the correct interface in the container.
=> Work around webpack-dev-server hostname checking requirement

app/components/layout/Navigation/MyBuilds/build.js, app/components/pipeline/Header/index.js, app/components/shared/Dialog.js, app/components/shared/Popover/index.js, package.json, yarn.lock
[styled-components v2](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) just landed!
We can finally dust off the old test branch which used `attrs` rather than `defaultProps`! Hooray!
=> Upgrade to styled-components v2

app/components/shared/Menu/button.js
This adds a couple of extra pixels of clearance to `MenuButton`s so that `Badge`s contained within them don’t expand their size. It also simplifies their structure slightly.
=> Accommodate badges in MenuButtons

app/components/agent/Show.js
We seem to have missed a field in the graphql query required for showing the agent priority on the new agent show page, so here's a tiny change to include it!
I wonder if we should be showing priority in the agent index as well?
=> Ask GraphQL for agent priority, too

app/components/agent/Index/quick-start.js, app/css/main.css
This updates our monospace font stack to include SFMono, as well as Liberation Mono for better Linux support.
This brings out mono stack more in line with that of GitHub!
=> Use tidier monospace font stack

app/components/pipeline/CreateBuildDialog.js
A small fix for this tweet:
https://twitter.com/RobStuttaford/status/870509925016813573
=> Prevent Create Build dialog submit without required fields

app/components/agent/Index/row.js, app/components/agent/Show.js, app/components/agent/state-icon.js
This means that users who don’t have permission to view a job do not see agents running them as idle; instead they’re told they’re busy with something they can’t see!
This also updates the `AgentStateIcon` to be a Relay component defining its data requirements explicitly.
=> Update AgentStateIcon to use isRunningJob

app/components/build/AvatarWithUnknownEmailPrompt.js
This has been a little improvement that feels like it should’ve been here forever, but here we go!
This updates the email prompt component to better deal with GitHub’s private email addresses. Given they’re predictable, instead of prompting the user to add the email address to their account…
…let’s instead prompt them to link their GitHub account, which will _actually_ connect the builds and not require a weird email verification dance!
“Manage Connected Apps” takes the user to `/user/connected-apps` where they can add their GitHub account. We _could_ hypothetically make this link directly do the GitHub auth flow, but this component doesn’t (read: currently can’t!) actually check if an account is connected, and it feels like it’d be weird to do that straight from a build page.
It also …
=> Handle private GitHub emails in email prompt

app/components/member/Index.js, app/components/team/Members/index.js
Currently when you filter down users to a single user, it incorrectly pluralises the phrase "1 member" as "1 members":
With this change, it now shows "1 member":
=> Don't pluralize "members" for a single member

app/components/build/AvatarWithUnknownEmailPrompt.js, app/graph/schema.json
This builds on #295, adding support for buildkite/buildkite#2183’s Authorizations queries, thus only showing #295’s updated prompt for GitHub email addresses if the user hasn’t yet linked any GitHub account.
~The only blocker I foresee for this one is finishing buildkite/buildkite#2183’s specs!~ This has now been decoupled.
=> Make unknown author prompt GitHub account aware

app/components/shared/FormRadioGroup.js, app/components/team/Edit.js, app/components/team/Form.js, app/components/team/TeamNew.js
Things I've done in this PR:
Here's a screen grab of the "New" page:
And the "Edit" page:
=> Teams form tweaks

app/components/organization/Pipelines.js, app/components/organization/Show.js, app/components/organization/Welcome.js
When you hit the "New Pipeline" button when scoping the pipelines to a team, it'll send the team slug to the "New Pipeline" page so we can preselect it.
The preselection doesn't work yet, but this just sends it as a param.
=> Send the current team to the new pipeline page

app/components/organization/Teams.js
This essentially hides "visible" teams that you can see because of their privacy setting.
Ideally you'd be able to ask GraphQL to only return teams that you have that permission for and have the logic in the backend, but this is an easy change for now.
=> Only show teams that have pipelines that can be viewed

app/components/shared/Chooser/select-option.js, app/components/shared/Icon/permission-small-cross.svg, app/components/shared/Icon/permission-small-tick.svg, app/components/team/Members/role.js
I tried this:
And a slightly more verbose copy which looked a little better in the window:
What do you prefer @toolmantim? I went with the longer one in this PR.
=> Tweak maintainer copy in the team member role window

app/components/member/Show.js, app/components/shared/PageHeader/index.js, app/components/shared/TabControl/Tab.js, app/components/shared/TabControl/index.js, app/css/main.css
This makes a bunch of styling updates to the `<TabControl>`:
* Coloured/active bottom border goes over the grey line
* Hover styles
* Padding/margin tweaks
I'm still not 100% happy with bottom margin on it, but it seems like works best with panel bodies that also have buttons right below it.
Before:
After:
=> Tab layout tweaks

app/routes.js
I discovered that `onUpdate` actually runs when the page loads, as well
as on every route change. This means that we end up clearing flashes
when page loads, and in some cases - they don't even show at all
(depending on how fast the browser is).
By using `browserHistory` we _only_ get events when the route is changed
in Javascript, not when the page loads :ok_hand:
=> Use browserHistory events for flash clearing instead of the router

app/components/shared/PermissionDescription.js, app/components/shared/PermissionSelectOptionDescriptions.js, app/components/team/Members/role.js, app/components/team/Pipelines/access-level.js
The idea was to be able to use the `<PermissionsDescription>` component elsewhere too, like on the Invite User permissions chooser.
=> Use the new permission styles on pipelines too

app/components/team/Labels.js, app/components/team/Row.js
This removes the margin-bottom on team's without descriptions, which was messing with vertical centering. And removes the empty labels div if they're not a secret team.
=> Small margin fixes on the Teams list

app/components/member/Show.js
If the Teams feature flag is on, but the organization has it disabled, you see a "Teams" tab in a user’s settings…
This fixes the logic so that they need to have teams enabled for the Teams tab to show on users.
=> Only show User > Settings > Teams if Teams enabled

app/components/member/MemberTeamRow.js, app/components/team/Labels.js
They both look the same now on the "New Pipeline" page, and on the "Invite Users" page:
I also removed the left hand padding because I the indentation was kinda bugging when I was looking at it. We don't really have other fields that are indented so I thought perhaps this looks a bit more consistent?
=> Have a consistent style for the team selectors

app/components/shared/Autocomplete/Dialog/index.js
If you have a large number of users, the dialog is a bit unwieldy. And it's height suggests almost helps to reinforce the misconception that it might contain all users? (another issue)
This fixes the height to half the viewport height, and adds a overflow scroll:
I wanted to treat the empty case differently… say, for a small account, or if there are "no more users to add", but unfortunately I couldn't wrangle the components, so will leave that for another PR.
=> Add overflow scroll to autocomplete dialog

app/components/member/Index.js, app/components/member/Show.js, app/components/shared/PageHeader/description.js, app/components/shared/PageHeader/icon.js, app/components/shared/PageHeader/index.js, app/components/shared/PageHeader/menu.js, app/components/sso/Index.js, app/components/team/Index.js
Whilst doing the screenshots for the announcement, the icon size and margin for the Teams section was bugging me. So this PR reduces the icon size in the header, and tweaks the margins.
Before:
After:
=> Tweak Teams pager header icon size

app/components/audit_log/row.js, app/components/shared/CollapsableArea.js, app/components/shared/Icon/RevealableDownChevron.js
This extracts out the copy-pasta rotatable chevron code from Create Build and Audit Logs into a shared icon component, and in the process cleans up the Audit Log chevron sizing.
Before:
After:
=> Clean up the audit log reveal chevron

app/components/layout/Navigation/MyBuilds/build.js, app/components/organization/Pipeline/index.js, app/components/shared/JobLink.js, app/components/team/Pipelines/pipeline.js
Moved from #349 to it gets run in CI! Thanks, @ide!
>Pipeline names were emojified in some places but not all. I grepped for `pipeline.name` and converted the remaining places where emojification wasn't happening, with the exception of things like the document title where emojification doesn't make sense.
>
>Fixes #343
>
>Tested only with unit tests
=> Emojify pipeline names in a few places that were missing it

app/components/agent/Show.js, app/components/agent/state-icon.js, app/components/shared/JobLink.js, app/graph/schema.json
This adds a list of the last 5 builds to the Agent Show page. Showing the pass/fail status of these required one addition to the GraphQL schema!
See also: buildkite/feedback#264
=> Add a job history to the Agent Show page

app/components/shared/FriendlyTime.js, app/lib/__snapshots__/date.spec.js.snap, app/lib/date.js
@ticky I wasn't 100% sure on how to fix this. I found a bug where `seconds` wouldn't have an affect if `capitalised` was being set to true.
=> Fix showing seconds in FriendlyTime when capitalizing words

app/components/pipeline/Header/index.js
This change censors passwords included in repository URLs when they're shown in the Pipeline header.
I noticed that a few customers use HTTP Basic Auth for git authentication, and while that's not dangerous in and of itself, the fact that it means their credentials are shown in the top of their (and my, if I'm doing support for them!) screen on every page made me nervous.
To that end, this change makes any passwords included in a URL be replaced with up to 8 • characters. This doesn't stop people using HTTP basic auth, and hopefully the dots are well-understood enough as meaning "hidden password."
The password can of course still be harvested from the page, either via the JavaScript or GraphQL, but discouraging encoding passwords in our web UI is probably a separate change. :)
**Before:** …
=> Hide HTTP Basic Auth passwords in Pipeline Header

app/components/agent/Show.js
This adds an "and n more" message to the bottom of the job list if there are more than the 10 we display, so it's clear when an Agent has done more work than we're showing.
=> Extra build job message on Agents page

Dockerfile, docker-compose.override.yml, docker-compose.yml, package.json, yarn.lock
This is potentially controversial. 
The thinking behind this is to roll a docker container with the production js/css in it, such that the buildkite/buildkite docker stuff can depend on something that is known good and working. To do this, it runs webpack in the Docker build process and puts the `dist/` dir in the container and serves it with a plain 'ol http server rather than webpack-dev-server.
=> Move webpack dist into docker build

app/components/agent/Index/agents.js
If you start an agent with tag `tag=Value` and then try to search for it in the agents UI, you can only match it with `tag=value` — if you type `tag=Value` then it shows "0 matching agents"
This fixes the problem by making, which makes the search case sensitive in the same way the step agent targeting rules are.
Search is still slightly different to agent targeting, in that partial matches are allowed, and you can search for an agent name case insensitively. But I think this is an improvement.
The alternative is to make tag searching completely case insensitive. But I'm afraid that might lead people to think that agent targeting rules are the same?
=> Fix agent searching for upper case tag names/values

app/app.js, app/components/build/Header/index.js, app/components/build/Header/pipeline.js, app/lib/BootstrapTooltipMixin.js
This was part of a scheme to try to move these components’ data requirements to GraphQL.
This part ended up taking a bit longer than I’d hoped, but I guess it might still be a step in the right direction.
Components were converted using [Decaffeinate](http://decaffeinate-project.org), and [react-codemod](https://github.com/reactjs/react-codemod), with guest star [Prettier](https://prettier.io), and some hand-massaging to add PropTypes and make it pass our rigorous ESLint suite.
`BootstrapTooltipMixin` also made the jump despite being _quite_ legacy because it was required by one of the components I needed to move, and it otherwise isn’t loaded in time for the ES6 code to use it.
=> ES6ify pipeline header components

package.json, webpack/config.js, yarn.lock
Working around danielholmes/relay-compiler-webpack-plugin#5 by avoiding stdout for JSON generation, using stats-webpack-plugin.
Related: #365.
=> Restore bundle analysis functionality

app/components/pipeline/Header/index.js
- The "Builds" buttons previously had a left margin at sizes above 768px, while they remain on a separate line until after 992px.
- The mobile actions dropdown has been updated to have a left margin so the source control icon doesn't butt up against it.
=> Fix Pipeline Header responsive layout

app/components/agent/Jobs.js, app/components/agent/Jobs/index.js, app/components/agent/Jobs/row.js, app/components/agent/Show.js, app/components/icons/BuildState.js, app/components/icons/JobState.js, app/components/shared/JobLink.js, app/components/shared/JobTitle.js, app/routes.js
This adds a detailed history of jobs run on each Agent. Each job is shown, along with the time it was assigned to the agent.
It has full pagination support:
The zero-job case is handled as shown (though in the zero-job case there is no link to this view, so it will only be shown to those savvy enough to go exploring):
Clicking anywhere in the panel will take the user to the build page the job is from, with the job log opened.
The existing “Recent Jobs” section has been updated to match, and include two links to the new page (the “and n more” text, and the title which is included for when the overflow text isn’t shown):
fixes buildkite/feedback#286
=> Add a detailed job history for Agents

app/components/agent/Show.js
This promotes the jobs section on agent pages to always show, even if the agent hasn’t run a job yet;
=> Always show the Jobs section on Agent pages

app/components/organization/SettingsMenu.js
This allows anyone who can get to the organisation settings to see the teams button.
=> Always show the teams button in organization settings

app/components/build/Header/pipeline.js, app/components/build/Show.js
This change starts grouping steps/jobs in the UI together if they're part of a "retry group".
Here, jobs in the main list are grouped together:
I've also opted to hide retried jobs by default in the pipeline. I'll post more about this internally.
=> Immutable Retry Groups UI (Part 2)

app/components/user/graphql/GraphQLExplorerConsole.js, app/components/user/graphql/consoleState.js, app/graph/schema.json, app/lib/RelayPreloader.js, app/queries/GraphQLSnippet.js, app/routes.js
This change adds a "Share" button to the console allowing peeps to share a GraphQL query to others. This is 1000% useful for support and community where peeps are like "how do I do `x` in GraphQL"
=> "Share" button in the GraphQL Console

app/components/pipeline/schedules/Edit.js, app/components/pipeline/schedules/Form.js, app/components/pipeline/schedules/Index/index.js, app/components/pipeline/schedules/Index/row.js, app/components/pipeline/schedules/Show/index.js, app/components/shared/FormCheckbox.js, app/mutations/PipelineScheduleCreate.js, app/mutations/PipelineScheduleUpdate.js
Previously, PipelineSchedules would be disabled and there was no indication other than no builds being generated, and the "next build" in the UI becoming further and further in the past that it was disabled. This exposes both the "disabled" state and failure messages in the UI, and allows re-enabling it from the error message itself.
This PR does not address taking ownership of a Schedule in order to re-authorise the schedule itself, but this would be a good next step.
=> Expose the error states possible for a PipelineSchedule in the UI

yarn.lock
Some dependencies had issues with Node 10.1 (the current version shipped in Homebrew) so this updates those involved so we don’t run into crashes in the node stdlib! 😅
=> Bump dependencies for Node@10.1 compatibility

webpack/config.js
Source maps haven’t worked properly on Production for a bit.
This ultimately means errors we’re getting in Bugsnag haven’t been particularly easy to read!
This re-enables producing proper source maps in prod.
On one hand, it feels weird to present this to end users, but then again this only reveals exactly the code we’re already shipping here, so it’s probably fine! There’s [an alternative option](https://docs.bugsnag.com/platforms/browsers/js/source-maps/#source-map-upload) if we only wanted to push these up specifically for the benefit of Bugsnag, too.
=> Fixed production source maps

app/css/annotation-body.css
Slightly tweak our annotation styles to give `<details>` siblings sligthly nicer padding, like a `<p>` when open, straight adjacent otherwise.
=> Style tweaks for nicer annotations

app/components/agent/Index/row.js, app/components/agent/Show.js
Some customers have custom Agents which do not advertise a version. This updates the bits of the UI which get a little confused about this to handle it correctly.
=> Handle empty agent versions

app/components/Main.js, app/components/layout/Flashes/flash.js, app/components/layout/Flashes/index.js, app/components/layout/Footer/index.js, app/components/layout/Navigation/MyBuilds/index.js, app/components/layout/Navigation/index.js, app/stores/FlashesStore.js
This fixes a few minor oversights in our UI, where it’s not checking for the presence of objects before rendering based on them. There are a few situations where the viewer or organization information might be missing, so this updates components which would previously fail to render in this state to handle them gracefully. This state is usually encountered by staff during support, though.
=> Improve UI resilience

app/css/annotation-body.css
As reported by @tessereth, in an annotation body if there's a nested `<detail>` inside a closed `<detail>`, you get this additional margin appearing between them:
This fixes it so that we're only adding margin to the correct summary element.
=> Fix incorrect margin of nested, closed annotation summaries

app/components/docs/01-ubuntu.mdx, app/components/docs/02-debian.mdx
We still need to support Ubuntu 14.04 which is an LTS release supported until April 2019, but 12.04 is long gone, and ending with 15.04 is embarrassing.
And Debian 9.x has been out since mid last year, and works fine.
=> Bump OS versions in agent instructions

app/components/pipeline/CreateBuildDialog.js
Pulled out of #519 because it ended up not needing it anymore, but it’s still a useful change.
=> Flowify Create Build Dialog

app/components/layout/Navigation/index.js, app/lib/RelayPreloader.js, app/lib/permissions.js
This change makes sure we check the `pipelineView` and `agentView` permissions in the navigation header.
=> SSO2: Respect `view` permissions in the navigation header

app/components/layout/Navigation/index.js, app/components/member/InvitationRow.js, app/components/member/Row.js, app/constants/OrganizationMemberSSOModeConstants.js
This change adds a few badges about the place.
Invitation rows now have an "Administrator" badge (it used to just be gray words), now it's a badge:
I've applied the same treatment here:
The org switcher in the nav will now check to see if can view pipelines inside it, and if it can't (because of SSO) it'll show:
=> SSO2: Badges

app/components/member/Edit/form.js, app/components/member/InvitationRow.js, app/components/member/New.js, app/components/member/Row.js, app/mutations/OrganizationInvitationCreate.js, app/mutations/OrganizationMemberUpdate.js
Nothing too interesting. This change adds a "Single Sign-On" section to invitations and member edit allowing you to modify the `sso.mode` attribute.
I also updated the "Administrator" section (was a checkbox) to be inline with the "Role" section we use on the invitation screen.
Here's the new member edit page:
And the invitation page:
The new "Single Sign-On" section doesn't appear unless you've configured an SSO2 provider.
=> SSO2: Added "Single Sign-On" options to the UI

yarn.lock
frontend node has been thrashing my cpu. @matthewd noticed while yarn-ing in frontend that fsevents was failing to compile, something I'd noticed too when yarn-ing from scratch, and also had a thrashed cpu. Updating fsevents seems to solve the issue. It also looks like it was holding back node-pre-gyp which was also holding back a bunch of transitive dependencies, so some of those are updated here, too.
=> Leave my cpu alone

app/components/audit_log/Drawer/actorSection.js, app/components/audit_log/row.js
The audit log data model says that actors can be optional. This change just tweaks the UI so it doesn't break when showing an audit log with no user.
=> Very basic handling of showing audit logs with no actor

app/components/layout/Navigation/index.js, app/components/member/Teams/index.js, app/components/organization/SettingsMenu.js, app/lib/RelayPreloader.js
Like this:
Currently this button only shows if you're a team admin, but it's now based on the `teamView` permission which `true` if the organization has enabled teams.
The button *doesnt* show if your organisation admin, at which point just "Settings" shows.
=> Show the "Teams" button in navigation (most of the time)

app/components/shared/Popover/calculate-viewport-offsets.js
This updates calculateViewportOffsets to handle the “safe area” as margins on current Apple flagship phones.
=> Add support for iPhone X "safe area"

app/components/build/Header/index.js, app/components/organization/Pipeline/build-tooltip.js
Some builds are created without an author (some SCMs send us 0 information about authorship). Our UI assumes there's always a user.
This is just a quick patch to make sure the pages don't blow up if there isn't a user around.
=> Fix cases where there isn't a build author

package.json
Mainly just allows tests in `__tests__` dirs too, as is jest default.
=> Some extra jest config for better living

.eslintrc.yml, .flowconfig, webpack/config.js
Commit log has the changes, but to repeat here with some more detail;
- Allow Webpack to resolve module paths that are within `app/*` to be resolved in imports using a module path, not a relative one. This makes refactoring code around on the filesystem a _lot_ easier as you don’t have to wrestle with relative paths, it also has huge gainz for find-replacing, etc etc. Of course both relative and modules imports continue to work, but using module imports for all our code is so much easier on the brain.🧠✨
- **Before** https://github.com/buildkite/frontend/blob/9b027afcc6f41ddd14e38b436cf5814e320aae76/app/components/user/TwoFactor/RecoveryCodes/dialog.js#L7-L11
- **After** https://github.com/buildkite/frontend/blob/c4dc7bd0794ceae995c040e3f2885cd94a76d2ea/app/components/user/TwoFactor/Recover …
=> Some workflow tweaks

app/components/layout/Navigation/MyBuilds/index.js
Need to guard against `undefined` when accessing `viewer.scheduledBuilds` & `viewer.runningBuilds`. Because we’re selectively `@include`-ing these fields there appears to be a potential race condition around them being present.
=> Fix undefined data race condition from Relay @include field

app/components/audit_log/row.js, app/components/shared/TabControl/Tab.js, app/css/index.js, app/css/variables.js
Undoes the hardcoding in #679 by fixing the CSS variable importing, by only importing `variables.css` file, which is probably clearer and faster anyhow.
=> Fix loading of CSS variables in JS

codemods/no-relative-required.js
Had this lying around from a previous project. I won’t run it just yet as it touches ~134 files, but I’ll add it here for visibility and look to run it soon and then follow up with another PR.
You can test it out locally using the following command from the root of the Frontend repo.
```
jscodeshift app/ --transform codemods/no-relative-required.js
```
=> Codemod for re-writing all our relative paths to ones resolved by “app/”

app/components/layout/Navigation/index.js, app/lib/RelayPreloader.js
Not very exciting... This tweaks the behaviour around rendering the "current" so it won't render the org as "current" if it needs SSO.
This is to keep the behaviour consistent to when you're not part of the org to begin with.
=> Don't show the org as "current" in the nav if it requires SSO

app/components/user/TwoFactor/index.js
Somehow I dropped this patch out of the MFA work.
This ensures that we don’t render the MFA UI when the user has no password set.
=> Don't render the MFA UI if the user has no password set.

app/components/RecoveryCodeList/index.js, app/components/user/TwoFactor/RecoveryCodes/index.js, app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureActivate/index.js, app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureRecoveryCodes/index.js, app/components/user/TwoFactor/TwoFactorConfigure/index.js, app/components/user/TwoFactor/index.js, package.json, yarn.lock
A bunch of random stuff in here! I tightened some stuff up and made the recovery code boxes consistent between viewing and saving them.
A few notable changes:
=> Random visual tweaks to MFA components

app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureActivate/buildkite.svg, app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureActivate/index.js
I noticed the QR image doesn't quite match the code size most of the time:
This cleans it up most of the time, and also moves it down a tad (the mark should always sit a bit lower than completely centre):
=> Sharpen and minify the BK QR image

app/app.js, app/public-path.js
This uses a special webpack variable, `__webpack_public_path__`, to optionally allow dynamically overriding the asset host on the fly at runtime using `window._frontendPublicPath`:
https://webpack.js.org/guides/public-path/#on-the-fly
This means we can use the same assets baked into the Docker image for testing by hosting them in a static directory and overriding the public path, as well as the asset cdn on the production assets, or download and use them locally in development too. I also want to try putting up a cloudfront version of  `buildkite.com` with a static `/_frontend` (and `/assets`, etc) so we can same-domain all the assets and utilise http/2.
It has to be in a separate module imported at the top of the entry point to be effective due to load and execute ordering.
After this …
=> Allow overriding public path dynamically

Dockerfile, Procfile, docker-compose.yml, package.json, webpack/config.js
Remove fixed `$FRONTEND_HOST`. Remove the public path by default, too. We can set a public path using window._frontendPublicPath at runtime now. This makes a manifest with relative URLs:
```json
{
"" : {
"js" : [
"0.chunk.js",
"1.chunk.js"
],
"jpg" : "ff9cb1e83fd7a9ee6c7e34f43b9a85e4.jpg",
"png" : "4b65a0c3d4a3c63cc7873be27a9c6cd8.png"
},
"app" : {
"js" : "app.js"
},
"emoji" : {
"js" : "emoji.chunk.js"
},
"vendor" : {
"js" : "vendor.chunk.js"
}
}
```
But when running webpack dev server it needs to do middleware magic via a separate host, so make sure it always has an explicit public path, which will be output in the manifest, overriding buildkite's default `$FRONTEND_HOST` in development and preserving hot module replacement gear:
```json
{
"" : {
"js" : [ …
```
=> Remove FRONTEND_HOST

app/components/shared/FormMarkdownEditorField.js
Allows consumers to detect changes to the textarea, as the standard 'change' DOM events don't fire. This also fixes the autoresize not happening when an upload is completed.
=> Add an onChange property to the Markdown editor

app/components/pipeline/Header/index.js, app/css/container.css
Noticed that our build pipelines headers are not in great shape at the moment. 😐
Things get pretty bad with super long descriptions...
But even with short descriptions things are pretty janky.
| Authenticated | Anonymous   |
| :-------------: |:-------------:|
| <img width="616" alt="screen shot 2019-01-11 at 2 53 43 pm" src="https://user-images.githubusercontent.com/18076/51012364-e57b4800-15b0-11e9-924e-32c21424bcbd.png"> | <img width="616" alt="screen shot 2019-01-11 at 2 54 35 pm" src="https://user-images.githubusercontent.com/18076/51012375-e7dda200-15b0-11e9-9060-f610f89bd224.png"> |
| <img width="880" alt="screen shot 2019-01-11 at 2 53 51 pm" src="https://user-images.githubusercontent.com/18076/51012365-e57b4800-15b0-11e9-877c-3ab99adfee36.png"> | <img width="879" alt="screen shot …
=> Fix header styling

app/components/icons/BuildState.js, app/components/icons/__snapshots__/BuildState.spec.js.snap, app/components/shared/Spinner.js, app/css/animations.css
Looks like we have a double animation happening inside our spinner, which goes against the performance comment at the top of the file. This removes the nested `animation-spin` and fixes up the other uses of the class to work with the new values.
=> Remove nested animation-spin in the spinner

app/components/shared/Chooser/select-option.js, app/components/shared/PermissionDescription.js
It seems the unicode character we were using in our choosers can't be coloured anymore in Safari, and our chooser has been broken as you can't tell which one is selected. This fixes that by using our icon, and makes a few small tweaks (like adding the hover background to the selected option as well).
Before:
After:
=> Fix the chooser select icon and positioning

app/app.js, app/components/OrganizationShow/Pipeline/index.js, app/components/OrganizationShow/__tests__/OrganizationShow_test.js, app/components/agent/Index/AgentTokenItem.js, app/components/agent/Index/row.js, app/components/agent/Show.js, app/components/pipeline/Header/index.js, app/components/shared/Badge.js, app/components/shared/BetaBadge.js, app/components/shared/FormRadioGroup.js, app/components/shared/PipelineStatus/index.js, app/css/colors.css, app/css/variables.css
This cleans up all our badges (text and numbers) to use a single, consistent component with decent contrast and no more all-caps. It also exposes a BetaBadge component we can use for badging beta features (there's a matching Rails partial which makes use of it).
Before:
After:
=> Make the public badge the same as the beta badge

app/components/build/Header/index.js
Currently on master the build footer looks like this, and uses `color-inherit`:
The idea was to fix the colour in the container, and to pick better colours, but we need to get the layout fixes done first, so this brings it back to matching the current colour on production:
=> Make build footer text colour muted again

app/components/agent/Index/quick-start.js, app/components/agent/Index/row.js, app/components/agent/Show.js, app/components/member/Teams/row.js, app/components/pipeline/teams/Index/row.js, app/components/shared/JobLink.js, app/components/shared/User.js, app/components/team/Edit.js, app/components/team/Members/row.js, app/components/team/Pipelines/row.js, app/graph/schema.json
Now we've updated the link colours, the lists full of green seem a bit harsh. This cleans up the agent/teams/pipelines/members list links, and makes them consistently styled with black/lime-hover.
It also links to the users from the Team’s Members list, to make it consistent with the Team’s Pipelines list.
=> Cleanup index link styles

app/components/build/AnnotationsList.js, app/lib/RelayPreloader.js
We currently only display the first 5 annotations for any build. I've used the `ShowMoreFooter` component for consistency, but I'm not sure if I'm happy with how it fits into the page here. Thoughts?
Here's the gist I used for >5 annotations.
https://gist.github.com/eleanorakh/ed0ccde127431e46e92d29b93b0fe44a
=> Show more annotations button
