app/components/layout/Navigation.js, app/components/shared/Badge.js, app/css/custom-basscss-responsive-states.css, app/css/main.css, app/css/transitions.css
=> Improve nav bar on mobile

app/components/layout/Navigation.js, app/components/user/BuildsCountBadge.js, app/css/transitions.css
Hides the badge when it's zero:
I've also reduced the vertical size of the dropdowns and removed the borders. Not 100% with these, but getting closer.
=> My Builds tweaks

.babelrc, .buildkite/eslint.sh, .buildkite/pipeline.yml, .buildkite/webpack.sh, .gitignore, app/app.js, app/components/build/CommentsList.js, app/components/shared/CollapsableFormField.js, app/components/shared/FormTextField.js, app/components/shared/FriendlyTime.js, app/graph/schema.json, app/lib/friendlyRelativeTime.js, package.json, webpack/config.js, webpack/emoji-loader.js
=> Import Legacy Webpack Components

app/app.js, app/components/layout/Footer.js, app/css/hover-fading.css, app/css/hover-underline.css, app/css/main.css
Looks just like the current one, but it's in React, and uses Basscss
=> Converted the in-app footer to React

app/components/team/Pipelines/index.js, app/components/team/Pipelines/row.js, app/mutations/TeamPipelineDelete.js
Following up buildkite/buildkite#1154 with some frontend to make it work:
This looks pretty ugly, but we don't have a nicer confirmation thingo.
Thoughts?
=> Allow forcing team pipeline removal

app/app.js, app/components/shared/FormInputErrors.js, app/components/shared/FormInputHelp.js, app/components/shared/FormInputLabel.js, app/components/shared/FormTextarea.js, app/css/legacy.css, app/css/main.css
=> Add textarea to frontend repo

app/components/layout/Navigation/index.js
My Builds is so handy that you want it on the nav bar on mobile as well
=> Show My Builds on the nav on small screens

app/components/layout/Navigation/dropdown-button.js
https://bugzilla.mozilla.org/show_bug.cgi?id=984869
Fixed:
=> You can't apply flex on <button> elements

app/stores/PusherStore.js
=> Fire a connected event on pusher connected

app/css/btn-primary.css
Not this:
But this:
Needed for buildkite/buildkite#1316
=> New primary is lime

app/components/organization/Pipeline/build.js, app/graph/schema.json
Cope with unregistered users who still have names and emails.
=> Unregistered user

.buildkite/eslint.sh, app/app.js, app/lib/RelayPreloader.js
The `RelayPreloader` class gives us the ability to bootstrap data from the server into Relay on page load - helping us get rid of the spinners!
=> Added a RelayPreloader class to load teams and organization information

app/components/shared/Button.js, app/components/team/Members/row.js, app/components/team/Pipelines/row.js
Whoops! I totally borked it.
This fixes #43
=> Fix the teams "Remove" buttons

app/components/layout/Navigation/index.js
fixes #51 
Also includes changes to resolve ESLint warnings within the navbar
=> Correct Buildkite logo clickable area in navigation

app/app.js, app/components/agent/Index.js, app/components/agent/Row.js, app/components/agent/Show.js, app/components/layout/Navigation/index.js, app/components/layout/Navigation/navigation-button.js, app/components/organization/Pipeline/build-tooltip.js, app/components/shared/FriendlyTime.js, app/components/shared/Panel/row.js, app/components/shared/RevealButton.js, app/css/hover-colors.css, app/mutations/AgentStop.js
=> Create new Agents list

app/components/organization/Pipeline/graph.js, app/components/organization/Pipeline/index.js
Extra stuff that got done along with the stuff in #61
=> Fix some ESLint smells in the Pipeline stuff

app/lib/Emoji.js, webpack/emoji-loader.js
This reduces the size of the resultant emojis.js more than half in dev, but is an optional enhancement to #69.
=> Index emoji the old way

app/components/user/BuildsDropdown/build.js, app/css/emoji.css, app/lib/Emoji.js, webpack/emoji-loader.js
This updates our emoji handling to;
- make use of relative font sizes, everywhere (emoji are 1.25 times font size unless otherwise specified), and align more nicely with text
- remove nearly all special cases (special cases which remain are _truly_ special; not just setting what would be that same relative font size)
- allow copying unicode emoji
- disable dragging (where supported!)
- make ESLint happier about the emoji-loader
=> Unify and simplify emoji style handling

app/app.js, app/components/api_access_token_code/APIAccessTokenCodeAuthorize.js, app/components/organization/Pipeline/index.js, app/components/organization/Pipelines.js, app/components/organization/Show.js, app/components/user/BuildsDropdown/index.js, app/lib/RelayPreloader.js
=> Optimize preloading of Pipelines

app/components/organization/Pipeline/index.js, app/components/organization/Teams.js
Work in progress; hides the graph and stats on small screens
=> Pipeline responsivity tweaks

app/components/icons/BuildState.js, app/components/organization/Pipeline/graph.js, app/components/organization/Pipeline/status.js, app/lib/RelayPreloader.js
Blocked builds will now show with the correct icon and will appear in the graph
=> Added support for the new `blocked` state on the Pipelines page

app/components/organization/Pipeline/bar.js, app/components/organization/Pipeline/graph.js, app/components/organization/Pipeline/index.js, app/css/animations.css
=> Loading animation for the pipeline graph

app/components/icons/BuildState.js, app/components/organization/Pipeline/graph.js, app/components/organization/Pipeline/status.js, app/lib/RelayPreloader.js, app/lib/__snapshots__/builds.spec.js.snap, app/lib/builds.js
Show scheduled builds as features build, and in the graph:
Also tweaks colours and icons slightly.
/cc @toolmantim
=> Pipelines page — icon/graph tweaks

app/app.js, app/lib/__snapshots__/jobs.spec.js.snap, app/lib/jobs.js, app/lib/jobs.spec.js
- replaces `JobDurationComponent`
=> Make a tested `jobTimer` method

app/components/layout/Navigation/index.js, app/components/user/BuildsCountBadge.js, app/stores/PusherStore.js, webpack/config.js
up-a-level (`../`) paths need not be preceded with `./`
=> I was getting confused by these dots; remove some!

app/app.js, webpack/config.js
counterpart to buildkite/buildkite#1588
=> Only load bugsnag if its vars are set

app/app.js, app/components/organization/AgentsCount.js, app/lib/number.js, app/lib/number.spec.js, package.json, yarn.lock
- add formatted number to agent count readout
=> Move number formatting to shared, tested library

app/components/Main.js, app/components/layout/Banners/index.js, app/components/layout/Banners/pipelines.js
=> Simple Banner Tech

app/components/layout/Navigation/index.js, app/components/shared/Emojify.js, app/components/shared/Emojify.spec.js, app/components/shared/__snapshots__/Emojify.spec.js.snap
- adds titles to Emojify component
- adds specs for Emojify component
- adds alt text to Buildkite logo
=> A buncha alt text

webpack/config.js
For:
https://app.intercom.io/a/apps/ggxoy3mj/inbox/all/conversations/6588460798
=> Add babel-polyfill for IE11

app/components/agent/Index/agents.js, app/components/agent/Index/search.js
Super basic proof of concept! The interaction could probably be improved
=> Added a basic search box to the new agents page

package.json, yarn.lock
Improves the output of type snob's warnings, with context and suggestions!
=> Upgrade type snob

app/components/agent/Index/agents.js
- when the entire list of agents is loaded, rather than pinging the server for searches, filter the local data set
- filter applies to;
- agent name
- agent meta data values (when there’s no `=` in filter)
- meta data key-values
- also sets the page size to 100 - this means _most_ customers should be exclusively doing local searches most of the time!
=> Sneaky local search for agents 🕵🏻‍♀️

app/components/shared/Duration.js, app/components/shared/Duration.spec.js, app/components/shared/__snapshots__/Duration.spec.js.snap, app/components/user/BuildsDropdown/build.js, app/lib/__snapshots__/date.spec.js.snap, app/lib/date.js, app/lib/date.spec.js
Updated, streamlined My Builds design from @toolmantim
=> My Builds refactor

.eslintrc.yml, app/components/icons/Favorite.js, app/components/layout/Navigation/support-dialog.js, app/components/user/BuildsDropdown/build.js, app/css/animations.css, package.json, yarn.lock
This implements the Support dialog’s bespoke animation using Styled Components instead of custom CSS.
Just fleshing out the idea of its use and seeing where it takes us!
=> Try out Styled Components on the Support dialog

app/components/agent/Index/agent-tokens.js, app/components/agent/Index/agents.js, app/components/agent/Index/index.js, app/components/agent/Index/installation.js, app/components/agent/Index/quick-start.js, app/components/layout/Navigation/support-dialog.js, app/components/shared/Dialog.js
=> Implement setup=true behaviour for Agents page

app/components/layout/Navigation/support-dialog.js, app/components/shared/Dialog.js
Previously it was different on Bootstrap pages!
=> Make support dialog consistent

app/components/organization/Pipeline/bar.js, app/components/organization/Pipeline/build-tooltip.js, app/components/organization/Pipeline/graph.js, app/components/organization/Pipeline/status.js, app/components/shared/Popover/anchored.js, app/components/shared/Popover/calculate-viewport-offsets.js, app/components/shared/Popover/index.js
I got kinda wheel-spinny on this on Friday so I’m going to put it here so it can either die or get worked on more later.
It’s probably going to be worthwhile to get working for the email popover, but I think the actual functionality for that is more important…
=> Centralise popover logic

app/components/agent/Index/agents.js
This switches the Agents list to update when it gets a push event. It also adjusts the automatic refresh interval to 15 seconds, and will only fetch once per 5-second window.
Fixes https://3.basecamp.com/3453178/buckets/1445180/todos/353039886, and partially addresses #139
=> Use push events for Agents List

app/components/agent/Index/index.js, app/components/agent/Index/installation.js, app/lib/RelayPreloader.js
Partially addresses https://3.basecamp.com/3453178/buckets/1445180/todos/323608010
=> Update Agent list relay preload data

app/components/build/AvatarWithUnknownEmailPrompt.js
Just looking into adding some Pusher gear and noticed some bits and pieces that could be cleaned up  + commented a little.
=> Some random avatar prompt code cleanups

app/components/agent/Index/agents.js, app/components/agent/Index/row.js, app/components/agent/Show.js, app/lib/RelayPreloader.js
Tweaked loading of the Agents Show page so have the browser just hang on you while it's performing necessity queries to load the page.
=> Tweaked data loading for Agents Show

app/components/agent/Index/installation.js, app/components/layout/Navigation/support-dialog.js, app/components/shared/Dialog.js
=> Slightly more generic dialog styles

app/components/agent/Index/agent-tokens.js, app/components/agent/Index/index.js, app/components/agent/Index/quick-start.js, app/components/agent/Index/row.js, app/components/agent/Show.js, app/components/agent/__snapshots__/shared.spec.js.snap, app/components/agent/shared.js, app/components/agent/state-icon.js, app/components/docs/05-docker.mdx, app/components/docs/09-aws/parameter-table.js, app/components/organization/Welcome.js, app/css/reset.css
Agent setup before/after:
AWS tab before/after:
Agent show page before/after (the after doesn't have the job warning message, because now that is only shown if the agent actually has a job assigned):
=> Clean up agent setup

app/components/agent/Index/agent-tokens.js, app/components/agent/Index/index.js, app/components/agent/Index/installation.js, app/components/shared/Dialog.js, package.json, yarn.lock
(padding was slightly tweaked after the video was taken)
=> 🎊 New "First Agent Connected" dialog

app/app.js, app/components/pipeline/CreateBuildDialog.js, app/components/pipeline/Header.js, app/components/pipeline/Header/builds.js, app/components/pipeline/Header/index.js, app/lib/RelayPreloader.js
=> Importing the Pipeline Header to Frontend

app/app.js, app/components/pipeline/Header/index.js, app/components/pipeline/SettingsMenu.js, app/components/pipeline/SettingsSection.js, app/components/pipeline/schedules/Edit.js, app/components/pipeline/schedules/Index/index.js, app/components/pipeline/schedules/New.js, app/components/pipeline/schedules/Show/index.js, app/components/pipeline/teams/Index/index.js, app/components/shared/Menu/button.js, app/lib/RelayPreloader.js, app/queries/Agent.js, app/queries/Build.js, app/queries/Organization.js, app/queries/Pipeline.js, app/queries/PipelineSchedule.js, app/queries/Team.js, app/routes.js
Components to add a side bar to the pipeline settings page.
=> Project Settings 2.0 Components

app/components/member/Index.js, app/components/member/InvitationRow.js, app/components/member/Row.js, app/components/organization/SettingsMenu.js, app/components/team/Index.js, app/components/team/Row.js, app/graph/schema.json, app/mutations/OrganizationInvitationResend.js, app/mutations/OrganizationInvitationRevoke.js, app/queries/OrganizationMember.js, app/routes.js
User view has been split off into #194
=> Port user management to React & GraphQL: Part 1, User & Invitation List

Dockerfile, package.json, webpack/config.js, yarn.lock
This upgrades our Webpack setup to v2
=> Upgrade to Webpack 2

app/app.js, app/css/legacy.css, app/css/main.css, package.json, webpack/config.js, yarn.lock
Reverts buildkite/frontend#195 as there's still quite a few more kinks that need ironing out
=> Revert "CSS assets"

app/components/member/Edit.js, app/components/member/Index.js, app/components/member/InvitationRow.js, app/components/member/Row.js, app/components/member/Show.js, app/graph/schema.json, app/mutations/OrganizationMemberDelete.js, app/mutations/OrganizationMemberUpdate.js, app/routes.js
=> Port user management to React & GraphQL: Part 2, User view

app/components/member/Edit.js, app/components/member/Index.js, app/components/member/New.js, app/components/member/TeamRow.js, app/components/pipeline/teams/Index/index.js, app/components/pipeline/teams/Index/row.js, app/components/shared/FormCheckbox.js, app/components/team/Suggestion.js, app/mutations/OrganizationInvitationCreate.js, app/routes.js
=> Port user management to React & GraphQL: Part 3, User add

app/css/background-colors.css, app/css/border-colors.css, app/css/colors.css, app/css/input.css, app/css/main.css
The current red isn't very useful, it's more like a dark red. This renames `red` to `dark-red` and makes `red` something more useful.
Before:
After:
=> Fix the color red

app/components/member/New.js, app/components/member/TeamRow.js
Nothing too major here, I added the `PageHeader` to be consistent with the "New Team" page. I also switched to a Radio group instead of a checkbox.
And added inline error messages
=> New user tweaks

app/components/team/Index.js, app/components/team/Show.js, app/graph/schema.json
=> Added pagination and searching to the teams index

app/components/pipeline/CreateBuildDialog.js, app/components/shared/CollapsableArea.js, app/components/shared/CollapsableFormField.js, app/components/shared/FormTextarea.js, app/css/btn.css, app/css/colors.css, app/css/hover-colors.css, app/css/main.css, app/css/outline.css, app/lib/number.js
Before:
After:
(the autofocus still works… I just expanded the Options before hitting the screenshot, and lost focus on the commit message field)
=> Clean up "New Build" dialog

app/components/agent/Index/installation.js, app/components/agent/Show.js
This fixes #139 and I’ve been wanting to ship it for a while.
It means those periodic requests won’t be started until the last one was completed!
=> Replace setIntervals with setTimeouts

app/components/pipeline/SettingsMenu.js
Instead of "Unknown" this shows "Repository" in the new project settings nav
=> Handle unknown/private repositories in new project settings nav

app/components/build/StateSwitcher.js
=> Fix pluralisation in the build switcher for 1 build

app/components/team/Members/index.js, app/components/team/Pipelines/index.js
=> Add counts to team management panes

app/components/member/Index.js, app/components/team/Index.js
=> Add PageHeader Icons to settings pages

app/components/pipeline/schedules/Index/index.js
=> Clean up schedules settings screen

app/components/build/StateSwitcher.js, app/components/pipeline/Header/builds.js, app/components/pipeline/Header/index.js, app/components/pipeline/SettingsMenu.js, app/components/shared/Button.js, app/css/btn.css, app/lib/__snapshots__/repositories.spec.js.snap, app/lib/repositories.js, app/lib/repositories.spec.js
=> New pipeline header layout improvements

app/components/pipeline/schedules/Form.js
Nicolas Huray pointed this out on Slack, figured I'd go ahead and open the PR.
=> Fix tiny, tiny typo

app/components/organization/Pipelines.js
This reduces the initial pipeline fetch to 100 pipelines, and then makes each subsequent page a 50-pipeline chunk.
We've had some feedback that the graphs are causing all sorts of slowdown for larger customers, and the only simple way to fix that would seem to be to make it less demanding overall!
should help with buildkite/feedback#247
=> Paginate main Pipelines page

app/lib/Emoji.js, app/lib/Emoji.spec.js, app/lib/__snapshots__/Emoji.spec.js.snap, package.json, yarn.lock
frontend counterpart to buildkite/emojis#67
=> Update support for Emoji 4.0 (Unicode 9.0)

app/lib/Emoji.js, app/lib/Emoji.spec.js, app/lib/__snapshots__/Emoji.spec.js.snap, package.json, yarn.lock
Reverts buildkite/frontend#270
=> Revert "Update support for Emoji 4.0 (Unicode 9.0)"

app/components/organization/Pipelines.js, app/graph/schema.json, app/lib/RelayPreloader.js
=> Pipeline list fixes

Dockerfile
This adds watchman to the Dockerfile which is needed for compling Relay Modern GraphQL queries
=> Watchman in Docker

app/components/agent/Index/agents.js, app/components/member/Edit/team-memberships/index.js, app/components/member/Index.js, app/components/organization/Pipelines.js, app/components/shared/LoadMoreFooter.js, app/components/shared/Panel/index.js, app/components/shared/ShowMoreFooter.js, app/components/team/Index.js, app/components/team/Members/index.js, app/components/team/Pipelines/index.js
This implements a basic proof of the new Connection-as-interface stuff in all the places we previously had an ad hoc implementation of more or less the same pagination!
=> Reusable “Show More” component

app/components/organization/SettingsMenu.js, app/components/pipeline/SettingsMenu.js, app/components/shared/PageHeader/index.js, app/components/team/Index.js
=> Self-enable teams support

app/components/member/Edit/form.js, app/components/member/Edit/index.js, app/components/member/Edit/remove.js, app/components/member/Show.js, app/components/member/Teams/chooser.js, app/components/member/Teams/index.js, app/components/member/Teams/row.js, app/components/member/Teams/team.js, app/routes.js
@ticky I used your `TabControl`, worked a treat!
=> Add tabs to "Member Edit"

app/components/organization/Pipelines.js, app/components/organization/Show.js, app/components/organization/Welcome.js, app/lib/RelayPreloader.js
If you don't have permission, we shouldn't show the button!
=> Respect `pipelineCreate` permission on the organisation show page

app/components/team/Edit.js, app/components/team/Show.js, app/components/team/TeamDelete.js
Works like it says on the tin!
=> Move the Team "Delete" button into the Settings tab

app/components/team/Show.js
=> Use <TeamLabels> in the teams header

app/components/shared/Badge.js, app/components/team/Labels.js
Also used in an upcoming pull request…
=> Use <Badge outlined> for team labels

README.md
This updates the readme to make it a little clearer what the current state of play is with the frontend repository.
This should help cases such as #303, where @KevinGrandon spent a bunch of time trying to get it running, only to find out it wasn't really at all possible.
Fixes #303
=> Clarify the current state of the frontend repo

app/components/member/MemberTeamRow.js, app/components/member/New.js, app/components/organization/Teams.js, app/components/pipeline/New/PipelineNewTeams.js, app/routes.js
=> Relay based Team Selector for the New Pipeline page

app/components/team/Form.js, app/components/team/Labels.js, app/components/team/Show.js
@toolmantim feel free to change the words and merge when you're happy!
=> Default Team Tweaks

app/components/team/Show.js
=> Remove old team label props

app/components/team/TeamNew.js
It's only the final submit button that should say "Create"
=> Create a Team → New Team

app/components/member/Teams/index.js, app/components/organization/Teams.js, app/components/team/Edit.js
=> Small teams tweaks

app/components/member/Teams/chooser.js, app/components/pipeline/teams/Index/chooser.js, app/components/team/Members/chooser.js, app/components/team/Pipelines/chooser.js
Updates based on your feedback @ticky!
=> Further Relay fixes for Chooser dialogs

app/components/audit_log/Drawer/actorSection.js, app/components/audit_log/Drawer/contextSection.js, app/components/audit_log/Drawer/eventSection.js, app/components/audit_log/Drawer/shared.js, app/components/audit_log/Drawer/subjectSection.js, app/components/audit_log/row.js
Some attempts at more event types in descriptions:
I was playing around with some styles, too, and omitting fields without data. React won't let me return a dt/dd without a parent so I had to make multiple dls :-(((
Also "an user", hmm. Might need a special case.
=> Audit descriptions

app/components/pipeline/Header/index.js
A supporting change to lead up to buildkite/buildkite#2304
=> Hide build header dropdown when it's empty

app/components/organization/Pipelines.js
Uses a local search if the entire data set is loaded already!
fixes buildkite/feedback#265
=> Allow local pipeline filtering

.buildkite/docker-compose.ci.yml, .buildkite/pipeline.yml, .buildkite/steps/webpack.sh, docker-compose.yml
My recent #358 broke master as I didn't realize that we used the container for CI. This copies the `dist` folder out of the docker container.
=> Copy dist/ folder back out to host for artifact upload

app/components/build/AvatarWithUnknownEmailPrompt.js
I've clicked this button many times incorrectly, and have seen lots of other people do it. I don't love this copy, but it's at least clearer.
=> Change unknown email prompt to something clearer

app/components/build/AvatarWithUnknownEmailPrompt.js
Fixing a typo from my previous PR.
=> Wanted an apostrophe not a quote

app/components/member/Teams/row.js, app/components/team/Members/index.js, app/mutations/TeamMemberDelete.js
Reverts buildkite/frontend#359
=> Revert "Switch to direct mutations for deleting team members"

app/components/docs/09-aws/index.mdx, package.json, yarn.lock
This upgrades us to the new beta build of Markdown Component Loader I cut this morning!
=> Markdown Component Loader v1.0

app/components/pipeline/Header/index.js, app/components/pipeline/SettingsMenu.js
This allows everyone to see the Pipeline Settings and Build Badges menu items.
=> Everyone can see build badge settings

app/components/member/Show.js, app/components/organization/SettingsMenu.js
Remove the feature flag check in the UI now that it's live
=> Remove TeamsLaunch feature flag check

app/components/audit_log/Index.js, package.json, webpack/config.js, yarn.lock
Just your regular yarn upgrade!
=> Yarn upgrade Relay, GraphQL and friends

yarn.lock
This is the last one for a while...
=> Yarn upgrade (jest, webpack-dev-server)

app/components/layout/Navigation/MyBuilds/index.js, app/components/shared/Dialog.js, app/components/user/NewChangelogsBadge.js, app/css/transitions.css
A few things broke in #419, this fixes 'em. Pay particular attention to the changelogs badge, New Builds dialog and my builds counter.
=> Fix missed changes to transition-group APIs

app/components/layout/Footer/index.js
A quicker alternative to finding the link on https://buildkite.com/home
=> Add System Status link

app/components/member/New.js, app/components/team/TeamNew.js
If you find yourself on this page and you don't have permission to do this thing, we should show a message instead of rendering the form.
=> Don't render the "New Team" or "Invite User" form if you're not allowed

app/components/member/Show.js, app/components/pipeline/SettingsMenu.js, app/components/team/Index.js, app/lib/RelayPreloader.js
Means we can get rid of the ugly global feature thingy!
=> Infer whether teams are enabled from the `teamView` permission

package.json
=> Add a package script so you can `[npm,yarn] run flow`

app/components/user/graphql/GraphQLExplorerConsoleEditor.js, app/components/user/graphql/GraphQLExplorerConsoleResultsViewer.js, app/components/user/graphql/GraphQLExplorerExampleSection.js
This seems to be breaking deploys for the moment, going to try reverting it for now
=> Revert "Webpack 4 prep: Lazy Load CodeMirrors"

.buildkite/steps/deploy.sh, app/components/user/graphql/GraphQLExplorerConsoleEditor.js, app/components/user/graphql/GraphQLExplorerConsoleResultsViewer.js, app/components/user/graphql/GraphQLExplorerExampleSection.js
Reverts buildkite/frontend#601, restoring buildkite/frontend#578
~@keithpitt any idea why or how this was breaking things?~ I figured it out ;P
=> Reinstate "Webpack 4 prep: Lazy Load CodeMirrors"

app/components/user/TwoFactor/__generated__/configureRecoveryCodeRegenerationMutation.graphql.js, app/components/user/TwoFactor/configure.js
This wires up the bones of the code to handle recovery code regeneration for MFA. While the UI doesn't look great, it's likely there's going to be some more overarching UI changes soon so it's important to have the regeneration functionality in place.
Big thanks to Justin for helping me with the final bits of the mutation today 🙏✨
=> Regenerate recovery codes button

app/components/shared/TabControl/Tab.js
Just hardcode these to get things working. This isn’t awesome but I’m keen to get things fixed first and foremost.
=> Fix tab control active and hover states

app/routes.js
=> Remove 2FA feature flag from route

app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureActivate/index.js, app/components/user/TwoFactor/TwoFactorConfigure/TwoFactorConfigureRecoveryCodes/index.js
=> MFA cleanups

app/components/organization/SettingsMenu.js, app/components/shared/Menu/button.js, app/components/user/SettingsMenu.js
=> Show SSO status for each organization in the user settings menu

app/components/user/TwoFactor/TwoFactorDelete/index.js, app/components/user/TwoFactor/index.js
Was feeling a bit too wide! Just pulled it in a little bit.
Before:
After:
=> Tighten up the "Deactivate" box

app/components/user/SettingsMenu.js
=> Remove 2FA feature flip

app/components/build/StateSwitcher.js, app/components/pipeline/Header/builds.js, app/components/pipeline/Header/index.js
=> Added some extra test hooks for public builds stuff

app/components/layout/Footer/index.js
=> Feature community forum in footer

app/components/layout/Navigation/support-dialog.js, app/components/shared/Dialog.js
=> Prevents shufflejank on support dialog close

app/components/layout/Navigation/index.js, app/components/pipeline/CreateBuildDialog.js, app/components/pipeline/Header/index.js, app/components/pipeline/SettingsMenu.js, app/components/shared/FormDataList.js, app/components/shared/labelledFormComponent.js, app/graph/schema.json, app/lib/RelayPreloader.js
=> "New Build" dialog improvements

app/routes.js
=> Add a route we can iterate on the new pipeline things under

app/components/shared/ImageUploadField.js, package.json, yarn.lock
This is a proof-of-concept for making images resize on upload. It:
- Checks the image type and size, and
- If the image is big, loads it and resizes it
- If the resized image is smaller than the original, uploads the resized version
=> Try out blueimp-load-image for image resizing

app/components/OrganizationShow/index.js, app/components/team/TeamNew.js, app/components/user/TwoFactor/RecoveryCodes/index.js, app/components/user/TwoFactor/TwoFactorConfigure/index.js, app/components/user/TwoFactor/index.js, app/components/user/graphql/GraphQLExplorer.js, app/components/user/graphql/GraphQLExplorerConsole.js, app/components/user/graphql/GraphQLExplorerExamples.js, app/components/user/graphql/consoleState.js, app/lib/RelayModernPreloader/index.js, app/queries/GraphQLSnippet.js, app/routes.js
=> Render Relay Modern pages using a QueryRenderer directly

app/components/OrganizationShow/Pipeline/Graph.js, app/components/OrganizationShow/Pipelines.js
=> Prevent needless remounting/thrashing when order changes

app/lib/RelayPreloader.js
=> Add public field to preload

.eslintrc.js, app/app.js, app/components/AnonymousNavigation/index.js, app/components/Main.js, app/components/OrganizationShow/Pipeline/index.js, app/components/OrganizationShow/index.js, app/components/layout/Navigation/index.js, app/components/pipeline/Header/index.js, app/graph/schema.json, flow-typed/Features.js
Context for this change is https://3.basecamp.com/3453178/buckets/1970635/messages/1511706245
=> Public / Private Build headers and Fixes

app/lib/RelayPreloader.js
=> Fix preload of navigation

app/components/layout/Navigation/index.js
=> Don't display the org icon when the user is not a member of that org

app/components/build/Header/index.js
Cleans up the build header colours and text styles since #771 was merged
=> Fix the build header colors

app/components/build/Header/index.js, app/lib/commits.js
Sometimes it's 7, sometimes, it's 10.
=> Respect short commit length provided by the server

app/components/build/AnnotationsList.js
=> Add spacing and a label to annotation "Show more"
